# Generated by Django 3.2.8 on 2021-10-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0002_alter_request_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
